# ═══════════════════════════════════════════════════════════════════════════════
# nself-chat v0.9.2 Monorepo Workspace Configuration
# ═══════════════════════════════════════════════════════════════════════════════
#
# This workspace defines the frontend monorepo structure.
# Backend services are managed separately via nself CLI in .backend/
#
# Structure:
#   apps/*       - Platform-specific applications (web, mobile, desktop)
#   packages/*   - Shared packages (@nself-chat/core, api, state, ui, etc.)
#   tooling/*    - Development and build tools
#
# Usage:
#   pnpm install                          - Install all dependencies
#   pnpm -F @nself-chat/web dev          - Run web app
#   pnpm -F @nself-chat/core build       - Build core package
#   pnpm -r build                         - Build all packages
#
# ═══════════════════════════════════════════════════════════════════════════════

packages:
  # Frontend applications
  - 'apps/*'

  # Shared packages
  - 'packages/*'

  # Development tooling
  - 'tooling/*'
