name: üêõ Bug Report
description: Report a bug or unexpected behavior
title: '[Bug]: '
labels: ['bug', 'triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below to help us fix it.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here...

  - type: dropdown
    id: version
    attributes:
      label: …≥Chat Version
      description: Which version are you using?
      options:
        - 1.0.0 (latest)
        - 0.2.0
        - 0.1.x
        - main branch
        - Other (specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you running …≥Chat?
      options:
        - Local development
        - Vercel
        - Docker
        - Kubernetes
        - VPS/Traditional server
        - Other (specify below)
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Run `node -v` to get your version
      placeholder: v20.x.x
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using? (if applicable)
      placeholder: Chrome 120, Firefox 121, Safari 17, etc.

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which OS are you using?
      placeholder: macOS 14, Ubuntu 22.04, Windows 11, etc.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please copy and paste any relevant log output
      placeholder: |
        Paste error messages, stack traces, or logs here...
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched for existing issues before creating this one
          required: true
        - label: I have included all requested information above
          required: true
        - label: This is a bug in …≥Chat, not in my own code or configuration
          required: false
        - label: I can reliably reproduce this bug
          required: false
