-- PostgreSQL Initialization Script
-- Generated by nself build

-- Create database if not exists
SELECT 'CREATE DATABASE "nchat"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'nchat')\gexec

-- Grant all privileges
GRANT ALL PRIVILEGES ON DATABASE "nchat" TO postgres;

-- Create MLflow database if MLflow is enabled

-- Connect to the database
\c "nchat"

-- Create default schema
CREATE SCHEMA IF NOT EXISTS public;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO postgres;

-- Always create auth schema (required for auth service)
CREATE SCHEMA IF NOT EXISTS auth;
GRANT ALL ON SCHEMA auth TO postgres;
GRANT ALL ON ALL TABLES IN SCHEMA auth TO postgres;
GRANT ALL ON ALL SEQUENCES IN SCHEMA auth TO postgres;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA auth TO postgres;

-- Always create storage schema (may be needed later)
CREATE SCHEMA IF NOT EXISTS storage;
GRANT ALL ON SCHEMA storage TO postgres;
GRANT ALL ON ALL TABLES IN SCHEMA storage TO postgres;
GRANT ALL ON ALL SEQUENCES IN SCHEMA storage TO postgres;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA storage TO postgres;
